title: Andy Goulden's blog
email: not-real@email.com
description: >-
  This site is run by Andy Goulden.
baseurl: ""
url: "https://andygoulden.github.io"
github_username:  andygoulden
repository: andygoulden/andygoulden.github.io

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

theme: jekyll-theme-hacker