title: Andy Goulden's blog
email: not-real@email.com
description: >-
  This site is run by Andy Goulden.
baseurl: ""
url: "https://andygoulden.github.io"
github_username:  andygoulden

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
