title: Andy Goulden's blog
email: not-real@email.com
description: >-
  This site is run by Andy Goulden.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  andygoulden

# Build settings
theme: minima
plugins:
  - jekyll-feed
